- hosts: localhost
  connection: local
  gather_facts: no
  
  tasks:
  - name: Create & Start Container
    docker_container:
      name: webserver
      image: "lizen5/hello:2"
      state: started
      ports:
      - "80:8080"
